version: '3.8'

services:

  # ===============================
  # PostgreSQL 18
  # ===============================
  postgres:
    image: postgres:18beta1
    container_name: food-delivery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Fooddelivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Fooddelivery" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===============================
  # Redis
  # ===============================
  redis:
    image: redis:7.2-alpine
    container_name: food-delivery-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===============================
  # Spring Boot App
  # ===============================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-delivery-app
    restart: unless-stopped
    ports:
      - "9093:9093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Fooddelivery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
